Repository OpenSlides/openslides-auth-service, pull requests merged in 2023-12, with the labels that each got.

#175 Fix entityID in example_metadata_sp.xml
  auth/src/example_metadata_sp.xml
Labels: clean up

#176 Add `dependabot.yml`
  .github/dependabot.yml
Labels: enhancement

#211 Use postgres 15 images
  .github/startup-test/docker-compose.yml
  docker-compose.dev.yml
Labels: dependencies

#210 Update dependencies
  Dockerfile
  Dockerfile.dev
  Dockerfile.test
  auth/.eslintrc.js
  auth/jest.config.ts
  auth/libraries/pip-auth/requirements.txt
  auth/libraries/pip-auth/requirements_development.txt
  auth/package-lock.json
  auth/package.json
  auth/src/adapter/redis-database-adapter.ts
  auth/src/adapter/redis-message-bus-adapter.ts
  auth/src/api/interfaces/http-handler.ts
  auth/src/api/services/auth-service.ts
  auth/src/api/services/http-service.ts
  auth/src/api/services/secret-service.ts
  auth/src/api/services/ticket-service.ts
  auth/src/api/services/user-service.ts
  auth/src/index.ts
  auth/test/fake-redis-adapter.ts
Labels: dependencies

#217 Update typescript & linting rules
  .github/dependabot.yml
  auth/.eslintrc.js
  auth/package-lock.json
  auth/package.json
  auth/tsconfig.json
Labels: dependencies, clean up
