Repository OpenSlides/openslides-auth-service, pull requests merged in 2024-12, with the labels that each got.

#590 Kill sessions for user
  auth/libraries/pip-auth/authlib/auth_handler.py
  auth/libraries/pip-auth/authlib/session_handler.py
  auth/src/express/controllers/private-controller.ts
  auth/test/clear-sessions-by-user-id.spec.ts
Labels: enhancement

#594 Prevent login with inactive saml user
  auth/src/express/controllers/guardian.txt
  auth/src/express/controllers/not_is_active.html
  auth/src/express/controllers/saml-controller.ts
Labels: bug

#603 Include not_is_active.html when building
  auth/package-lock.json
  auth/package.json
Labels: staging
